{ pkgs, inputs, ... }: {
  environment.systemPackages = with pkgs; [
    kitty
    kdePackages.dolphin
    kdePackages.ffmpegthumbs
    kdePackages.kio-extras
    fzf
    ffmpeg
    mediainfo
    lsd
    rclone
    rsync
    rclone-browser
    btop-rocm
    bulky
    cliphist
    fastfetch
    fladder
    glow
    hyprshot
    jq
    losslesscut
    mpv
    nomacs
    ntfs3g
    obsidian
    ouch-rar
    qbittorrent
    restic
    ripgrep
    libreoffice-fresh
    wl-clipboard
    lutris
    protonup-rs
    noctalia-shell
    gum
    mangohud
    aria2
    pass
    mesa
    vulkan-loader
    libGL
    libGLU
    mkvtoolnix-cli
    wget
    proton-vpn
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    tesseract
    miktex
    texlab
    gnome-disk-utility
  ];
}
