{ pkgs, inputs, ... }: {
  environment.systemPackages = with pkgs; [
    pkgs.kitty
    pkgs.kdePackages.dolphin
    kdePackages.ffmpegthumbs
    pkgs.kdePackages.kio-extras
    pkgs.fzf
    pkgs.ffmpeg
    pkgs.mediainfo
    pkgs.lsd
    pkgs.rclone
    pkgs.rsync
    pkgs.rclone-browser
    pkgs.btop-rocm
    pkgs.bulky
    pkgs.cliphist
    pkgs.fastfetch
    pkgs.fladder
    pkgs.glow
    pkgs.hyprshot
    pkgs.jq
    pkgs.losslesscut
    pkgs.mpv
    pkgs.nomacs
    pkgs.ntfs3g
    pkgs.obsidian
    pkgs.ouch-rar
    pkgs.qbittorrent
    pkgs.restic
    pkgs.ripgrep
    pkgs.libreoffice-fresh
    pkgs.wl-clipboard
    pkgs.lutris
    pkgs.protonup-rs
    pkgs.noctalia-shell
    pkgs.gum
    pkgs.mangohud
    pkgs.aria2
    pkgs.pass
    pkgs.mesa
    pkgs.vulkan-loader
    pkgs.libGL
    pkgs.libGLU
    pkgs.mkvtoolnix-cli
    pkgs.wget
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
  ];
}
