return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPre", "BufNewFile" },
	opts = {
		ensure_installed = {
			"lua",
			"python",
			"javascript",
			"typescript",
			"tsx",
			"jsx",
			"bash",
			"json",
			"markdown",
			"dockerfile",
			"go",
			"gomod",
			"gowork",
			"gosum",
			"json5",
			"prisma",
			"ninja",
			"rst",
			"typst",
			"yaml",
			"toml",
		},
		highlight = { enable = true },
		indent = { enable = true },
	},
}
