config_version = 13

[audio]
enable_overdrive = true

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 1.0
    center = [ "workspaces" ]
    concave_edge_corners = false
    contact_shadow = true
    end = [ "tray", "ram", "network_rx", "notifications", "network", "bluetooth", "volume", "brightness", "battery" ]
    margin_ends = 0
    padding = 7
    panel_overlap = 0
    radius = 0
    shadow = false
    start = [ "custom_button_2", "clock", "media" ]
    thickness = 30
    widget_spacing = 11

[control_center]
shortcuts = []
sidebar = "none"
sidebar_section = "none"

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
enabled = false

[location]
address = "Katpadi, India"
latitude = 79.164691000000005
longitude = 12.972618000000001

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
position = "top_center"

[osd.kinds]
media = false

[plugins]
enabled = []

[shell]
avatar_path = "/home/sachin/Pictures/profile.jpeg"
external_ip_enabled = true
font_family = "JetBrainsMono Nerd Font"
panel_anchor_bar = "default"
polkit_agent = true
settings_show_advanced = true

    [shell.launcher]
    categories = false

    [shell.panel]
    clipboard_position = "bottom_center"
    floating_offset = 0
    launcher_position = "bottom_center"
    open_near_click_control_center = true

    [shell.screenshot]
    directory = "/home/sachin/Pictures/Screenshots"

[system.monitor]
network_poll_seconds = 1

[theme]
builtin = "Noctalia"
community_palette = "Lilac AMOLED"
pure_black_dark = true
source = "community"

[wallpaper]
directory = "/home/sachin/Pictures/Wallpapers"
edge_smoothness = 0.29999999329447746
transition = [ "fade" ]
transition_duration = 400

    [wallpaper.default]
    path = "/home/sachin/Pictures/Wallpapers/empty.png"

    [wallpaper.last]
    path = "/home/sachin/Pictures/Wallpapers/empty.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/sachin/Pictures/Wallpapers/empty.png"

[weather]
refresh_minutes = 5

[widget.clock]
format = "{:%H:%M %d-%m-%Y}"

[widget.custom_button_2]
custom_image = "/home/sachin/Pictures/Wallpapers/nixos.svg"
type = "custom_button"

    [widget.custom_button_2.actions]
    left = "panel-open control-center"

[widget.media]
artist_first = true
hide_when_no_media = true
max_length = 158
title_scroll = "always"

[widget.network]
show_label = false
show_vpn_label = true

[widget.network_rx]
label_min_width = 16
network_speed_compact = true
network_speed_unit = "mb"

[widget.notifications]
hide_when_no_unread = true

[widget.ram]
stat = "ram_pct"

    [widget.ram.actions]
    right = "exec btop"

[widget.workspaces]
active_pill_size = 2.7000000000000002
empty_color = "on_secondary"
occupied_color = "on_secondary"
scale = 1.05